version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-yarn-frontend-packages-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
            - v1-yarn-frontend-packages-
      - run:
          name: Install Frontend Dependencies
          command: |
            cd frontend
            yarn install
      - save_cache:
          name: Save Frontend Yarn Package Cache
          key: v1-yarn-frontend-packages-{{ .Branch }}-{{ checksum "frontend/yarn.lock" }}
          paths:
            - ./frontend/node_modules/
      - restore_cache:
          keys:
            - v1-yarn-backend-packages-{{ .Branch }}-{{ checksum "backend/yarn.lock" }}
            - v1-yarn-backend-packages-
      - run:
          name: Install Backend Dependencies
          command: |
            cd backend
            yarn install
      - save_cache:
          name: Save Backend Yarn Package Cache
          key: v1-yarn-backend-packages-{{ .Branch }}-{{ checksum "backend/yarn.lock" }}
          paths:
            - ./backend/node_modules/
      - run:
          name: Run Frontend ESLint Check
          command: |
            cd frontend
            yarn lint \
              --format junit \
              --output-file ~/repo/reports/eslint/frontend-lint-results.xml
      - run:
          name: create env file
          command: |
            cd frontend
            touch .env
            echo "SERVER_URL=testhost:4000" > .env
      - run:
          name: Run Frontend Jest
          command: |
            cd frontend
            yarn test \
              --ci \
              --collectCoverage \
          environment:
            JEST_JUNIT_OUTPUT_DIR: ~/repo/reports/jest
            JEST_JUNIT_OUTPUT_NAME: test-results.xml
      - run:
          name: Run Backend ESLint Check
          command: 'cd backend && yarn lint'
